### PR TITLE
Add SSL support

### PR DESCRIPTION
**Pull request by yagobski**
When the url is https you have problem with this curl 
Adding         curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
Solve the problem

### CODE REVIEW

**Comment by yagobski** [comment]
Please merge this improvment

**Comment by FZambia** [comment]
Since this removes check of SSL certificate I think disabling SSL verifying must be optional and on by default.

**Comment by yagobski** [comment]
Centrifugo can't verify ssl from phpcent. It is not working.

**Comment by FZambia** [comment]
phpcent verifies certificate of Centrifugo, not vice versa - you are most probably using self signed certificate so it does not pass a check

**Comment by sl4mmer** [comment]
@yagobski thnx 
you shoud set Transport  safety to UNSAFE explictly 
```php
\phpcent\Transport::setSafety(\phpcent\Transport::UNSAFE);
```

**Pull request merged**
